'use strict';

const pool = require('./pool');

const categories = [
  {
    name: 'Shoes & Footwear',
    slug: 'shoes',
    icon: '👟',
    sort_order: 1,
    description: 'Step up your style with our curated selection of athletic, casual, and premium footwear.',
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&h=400&q=80',
  },
  {
    name: 'Shirts & Tops',
    slug: 'shirts',
    icon: '👕',
    sort_order: 2,
    description: 'From crisp oxford shirts to everyday tees — find your perfect fit.',
    image_url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&h=400&q=80',
  },
  {
    name: 'Mobile Phones',
    slug: 'phones',
    icon: '📱',
    sort_order: 3,
    description: 'Latest flagship smartphones from Apple, Samsung, Google, and more.',
    image_url: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=800&h=400&q=80',
  },
  {
    name: 'Accessories',
    slug: 'accessories',
    icon: '🎧',
    sort_order: 4,
    description: 'Complete your look and tech setup with earbuds, watches, speakers, and more.',
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&h=400&q=80',
  },
];

const products = [
  // ── SHOES (8) ─────────────────────────────────────────────────────────────
  {
    name: 'Nike Air Max 270',
    slug: 'nike-air-max-270',
    category: 'shoes',
    brand: 'Nike',
    sku: 'NK-AM270-BLK',
    price: 149.99,
    compare_at_price: 189.99,
    short_description: 'Max cushioning meets sleek style with the largest Air unit in the heel.',
    description: 'The Nike Air Max 270 delivers a fresh take on Max Air cushioning with the largest Air unit yet in the heel. Its lifestyle design adapts seamlessly from the gym to the street, featuring a engineered mesh upper for breathability and a dramatic Air unit that provides all-day comfort.',
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.8,
    review_count: 2341,
    is_featured: true,
    is_new: false,
    tags: ['running', 'air max', 'cushioning', 'lifestyle'],
    attributes: { style: 'Lifestyle', closure: 'Lace-up', material: 'Mesh', sole: 'Rubber', available_sizes: ['7', '8', '9', '10', '11', '12'] },
    meta_title: 'Nike Air Max 270 — Maximum Comfort Sneaker',
    meta_description: 'Shop the Nike Air Max 270 with the largest Air heel unit yet. Free shipping on orders over $50.',
  },
  {
    name: 'Adidas Ultraboost 22',
    slug: 'adidas-ultraboost-22',
    category: 'shoes',
    brand: 'Adidas',
    sku: 'AD-UB22-WHT',
    price: 189.95,
    compare_at_price: 219.95,
    short_description: 'Energy-returning Boost midsole with a Primeknit+ upper for the ultimate run.',
    description: 'The Adidas Ultraboost 22 raises the bar for performance running. Primeknit+ hugs your foot for a sock-like fit while the Linear Energy Push system gives you a propulsive toe-off. BOOST midsole technology returns energy with every stride so you can keep pushing further.',
    image_url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.7,
    review_count: 1876,
    is_featured: true,
    is_new: false,
    tags: ['running', 'boost', 'performance', 'primeknit'],
    attributes: { style: 'Running', closure: 'Lace-up', material: 'Primeknit+', sole: 'Continental Rubber', available_sizes: ['6', '7', '8', '9', '10', '11', '12', '13'] },
    meta_title: 'Adidas Ultraboost 22 — Premium Performance Running Shoe',
    meta_description: 'Run farther with Adidas Ultraboost 22. Energy-returning BOOST cushioning and Primeknit+ upper.',
  },
  {
    name: 'Converse Chuck Taylor All Star',
    slug: 'converse-chuck-taylor-all-star',
    category: 'shoes',
    brand: 'Converse',
    sku: 'CV-CT70-BLK',
    price: 64.99,
    compare_at_price: 80.00,
    short_description: 'The timeless canvas sneaker that never goes out of style.',
    description: 'The Chuck Taylor All Star has been a cultural icon since 1917. This classic canvas high-top features a rubber toe cap, vulcanized sole, and the iconic ankle patch. Available in dozens of colorways — this is the sneaker that goes with everything.',
    image_url: 'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.6,
    review_count: 5412,
    is_featured: false,
    is_new: false,
    tags: ['canvas', 'classic', 'casual', 'icon'],
    attributes: { style: 'Casual', closure: 'Lace-up', material: 'Canvas', sole: 'Vulcanized Rubber', height: 'High-top', available_sizes: ['5', '6', '7', '8', '9', '10', '11', '12'] },
    meta_title: 'Converse Chuck Taylor All Star — The Original Canvas Sneaker',
    meta_description: 'Shop the iconic Converse Chuck Taylor All Star. Classic canvas high-top available in all sizes.',
  },
  {
    name: 'New Balance 574',
    slug: 'new-balance-574',
    category: 'shoes',
    brand: 'New Balance',
    sku: 'NB-574-GRY',
    price: 84.99,
    compare_at_price: 99.99,
    short_description: 'Heritage sneaker with ENCAP midsole cushioning and suede/mesh construction.',
    description: 'The New Balance 574 is an all-time classic that mixes heritage aesthetics with everyday comfort. The ENCAP midsole combines a soft polyurethane rim with a hard nylon plate for support and durability, while the suede and mesh upper brings a premium look and feel.',
    image_url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.5,
    review_count: 3210,
    is_featured: false,
    is_new: false,
    tags: ['lifestyle', 'heritage', 'encap', 'classic'],
    attributes: { style: 'Lifestyle', closure: 'Lace-up', material: 'Suede/Mesh', sole: 'ENCAP', available_sizes: ['7', '8', '9', '10', '11', '12'] },
    meta_title: 'New Balance 574 — Heritage Lifestyle Sneaker',
    meta_description: 'Shop the New Balance 574 with ENCAP cushioning and suede/mesh upper. Classic comfort every day.',
  },
  {
    name: 'Timberland Premium 6-Inch Boot',
    slug: 'timberland-premium-6-inch-boot',
    category: 'shoes',
    brand: 'Timberland',
    sku: 'TB-6IN-WHT',
    price: 199.95,
    compare_at_price: 229.95,
    short_description: '100% waterproof leather boot built for every trail and city street.',
    description: 'The Timberland Premium 6-Inch Boot is the original since 1973. Crafted from premium waterproof full-grain leather, it features a padded collar, anti-fatigue technology for all-day comfort, and a lug rubber outsole for superior traction on every surface. A cultural icon that bridges outdoor performance and streetwear.',
    image_url: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.7,
    review_count: 1543,
    is_featured: true,
    is_new: false,
    tags: ['boot', 'waterproof', 'outdoor', 'leather'],
    attributes: { style: 'Boot', closure: 'Lace-up', material: 'Waterproof Leather', sole: 'Lug Rubber', waterproof: true, available_sizes: ['7', '8', '9', '10', '11', '12', '13'] },
    meta_title: 'Timberland Premium 6-Inch Boot — Waterproof Leather',
    meta_description: 'Shop the iconic Timberland 6-Inch Boot. Waterproof leather, anti-fatigue technology, rugged rubber outsole.',
  },
  {
    name: 'Vans Old Skool',
    slug: 'vans-old-skool',
    category: 'shoes',
    brand: 'Vans',
    sku: 'VN-OS-BKWH',
    price: 69.99,
    compare_at_price: 84.99,
    short_description: "Vans' original skate shoe with the iconic side stripe.",
    description: "The Vans Old Skool is a classic skate shoe that made history as Vans' first-ever shoe to feature the iconic side stripe. Built with a sturdy canvas and suede upper, a padded tongue and collar, and a waffle rubber outsole that provides traction and boardfeel.",
    image_url: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.6,
    review_count: 4321,
    is_featured: false,
    is_new: false,
    tags: ['skate', 'classic', 'canvas', 'casual'],
    attributes: { style: 'Skate', closure: 'Lace-up', material: 'Canvas/Suede', sole: 'Waffle Rubber', available_sizes: ['5', '6', '7', '8', '9', '10', '11', '12'] },
    meta_title: 'Vans Old Skool — Classic Skate Shoe',
    meta_description: 'Shop the iconic Vans Old Skool. Canvas and suede upper with the signature side stripe.',
  },
  {
    name: 'Puma RS-X Reinvention',
    slug: 'puma-rsx-reinvention',
    category: 'shoes',
    brand: 'Puma',
    sku: 'PM-RSX-BLU',
    price: 109.99,
    compare_at_price: 129.99,
    short_description: 'Bold, chunky silhouette inspired by late-80s Running System technology.',
    description: 'The Puma RS-X Reinvention reimagines the late-80s RS running shoe as a bold lifestyle sneaker. The thick, multi-layered midsole, mesh and leather upper, and striking colorblocking make it an instant statement piece. Running System technology provides lightweight comfort.',
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.3,
    review_count: 876,
    is_featured: false,
    is_new: true,
    tags: ['chunky', 'lifestyle', 'bold', 'retro'],
    attributes: { style: 'Lifestyle', closure: 'Lace-up', material: 'Mesh/Leather', sole: 'EVA', available_sizes: ['7', '8', '9', '10', '11', '12'] },
    meta_title: 'Puma RS-X Reinvention — Bold Chunky Sneaker',
    meta_description: 'Shop the Puma RS-X Reinvention. Chunky silhouette with RS running technology and bold colorblocking.',
  },
  {
    name: 'ASICS Gel-Kayano 29',
    slug: 'asics-gel-kayano-29',
    category: 'shoes',
    brand: 'ASICS',
    sku: 'AS-GK29-BLK',
    price: 159.95,
    compare_at_price: 179.95,
    short_description: 'Stability running shoe with FF BLAST+ ECO cushioning and LITETRUSS technology.',
    description: 'The ASICS Gel-Kayano 29 is an elite stability running shoe designed for long distances. FF BLAST+ ECO cushioning provides superior energy return while LITETRUSS technology delivers dynamic motion control for overpronators. The engineered mesh upper keeps your foot cool and secure mile after mile.',
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.8,
    review_count: 1234,
    is_featured: false,
    is_new: true,
    tags: ['running', 'stability', 'gel', 'performance'],
    attributes: { style: 'Running', closure: 'Lace-up', material: 'Engineered Mesh', sole: 'AHAR+ Rubber', support: 'Stability', available_sizes: ['7', '8', '9', '10', '11', '12'] },
    meta_title: 'ASICS Gel-Kayano 29 — Stability Running Shoe',
    meta_description: 'Shop ASICS Gel-Kayano 29. FF BLAST+ ECO cushioning and LITETRUSS stability for long-distance runners.',
  },

  // ── SHIRTS (7) ────────────────────────────────────────────────────────────
  {
    name: 'Classic White Oxford Shirt',
    slug: 'classic-white-oxford-shirt',
    category: 'shirts',
    brand: 'UrbanThread',
    sku: 'UT-OXF-WHT-M',
    price: 44.99,
    compare_at_price: 59.99,
    short_description: 'Crisp cotton oxford with a tailored fit — the boardroom-to-brunch essential.',
    description: 'Crafted from 100% premium combed cotton, our Classic White Oxford Shirt features a spread collar, mother-of-pearl buttons, and a tailored fit that works equally well with chinos or jeans. Machine washable and wrinkle-resistant so it looks sharp from morning meetings to after-work drinks.',
    image_url: 'https://images.unsplash.com/photo-1621072156002-e2fccdc0b176?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.4,
    review_count: 987,
    is_featured: false,
    is_new: false,
    tags: ['oxford', 'cotton', 'formal', 'business'],
    attributes: { material: '100% Cotton', fit: 'Tailored', collar: 'Spread', sleeve: 'Long', available_sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'] },
    meta_title: 'Classic White Oxford Shirt — Tailored Cotton',
    meta_description: 'Shop the Classic White Oxford Shirt. 100% premium cotton, tailored fit, wrinkle-resistant.',
  },
  {
    name: 'Polo Ralph Lauren Classic Fit Polo',
    slug: 'polo-ralph-lauren-classic-fit',
    category: 'shirts',
    brand: 'Ralph Lauren',
    sku: 'RL-POLO-NVY-L',
    price: 98.50,
    compare_at_price: 125.00,
    short_description: 'The original polo shirt, refined — mesh cotton, iconic pony embroidery.',
    description: "The Polo Ralph Lauren Classic Fit Polo has defined casual American style since 1972. Knit from soft mesh cotton, it features a 2-button placket, the signature embroidered pony at the chest, and a clean straight hem. Available in the season's best colors.",
    image_url: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.7,
    review_count: 2103,
    is_featured: true,
    is_new: false,
    tags: ['polo', 'cotton', 'preppy', 'classic'],
    attributes: { material: 'Mesh Cotton', fit: 'Classic', collar: 'Polo', sleeve: 'Short', available_sizes: ['S', 'M', 'L', 'XL', 'XXL'] },
    meta_title: "Polo Ralph Lauren Classic Fit Polo — Iconic American Style",
    meta_description: "Shop the iconic Polo Ralph Lauren Classic Fit Polo. Mesh cotton, embroidered pony, timeless style.",
  },
  {
    name: "Levi's Relaxed Fit Graphic Tee",
    slug: 'levis-relaxed-fit-graphic-tee',
    category: 'shirts',
    brand: "Levi's",
    sku: 'LV-GTEE-WH-M',
    price: 29.99,
    compare_at_price: 39.99,
    short_description: '100% organic cotton tee with a relaxed fit and vintage Levi\'s graphic.',
    description: "Made from 100% organic cotton, the Levi's Relaxed Fit Graphic Tee features a classic crewneck, dropped shoulders, and a slightly oversized silhouette for effortless casual style. The vintage Levi's graphic adds character without trying too hard.",
    image_url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.3,
    review_count: 1456,
    is_featured: false,
    is_new: false,
    tags: ['tee', 'organic', 'casual', 'graphic'],
    attributes: { material: '100% Organic Cotton', fit: 'Relaxed', collar: 'Crew', sleeve: 'Short', available_sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'] },
    meta_title: "Levi's Relaxed Fit Graphic Tee — Organic Cotton",
    meta_description: "Shop Levi's Relaxed Fit Graphic Tee. 100% organic cotton with a vintage graphic and relaxed silhouette.",
  },
  {
    name: 'Tommy Hilfiger Slim Stripe Shirt',
    slug: 'tommy-hilfiger-slim-stripe-shirt',
    category: 'shirts',
    brand: 'Tommy Hilfiger',
    sku: 'TH-SLIM-STR-M',
    price: 79.00,
    compare_at_price: 99.00,
    short_description: 'Slim-fit poplin shirt with a classic horizontal stripe — smart casual perfected.',
    description: "Tommy Hilfiger's Slim Stripe Shirt is cut from 100% poplin cotton in a contemporary slim fit. The classic horizontal stripe print is a wardrobe staple that pairs with everything from tailored trousers to dark jeans. A small Hilfiger logo sits discreetly at the chest.",
    image_url: 'https://images.unsplash.com/photo-1602810319428-019690571b5b?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.4,
    review_count: 743,
    is_featured: false,
    is_new: true,
    tags: ['stripe', 'slim', 'poplin', 'smart-casual'],
    attributes: { material: '100% Poplin Cotton', fit: 'Slim', collar: 'Button-down', sleeve: 'Long', available_sizes: ['S', 'M', 'L', 'XL', 'XXL'] },
    meta_title: 'Tommy Hilfiger Slim Stripe Shirt — Smart Casual Poplin',
    meta_description: 'Shop Tommy Hilfiger Slim Stripe Shirt. 100% poplin cotton, contemporary slim fit.',
  },
  {
    name: 'H&M Oversized Linen Shirt',
    slug: 'hm-oversized-linen-shirt',
    category: 'shirts',
    brand: 'H&M',
    sku: 'HM-LIN-BEI-L',
    price: 34.99,
    compare_at_price: 49.99,
    short_description: 'Relaxed linen shirt with drop shoulders for a cool, effortless summer look.',
    description: 'Cut from a breathable linen blend, the H&M Oversized Linen Shirt is the perfect warm-weather essential. Dropped shoulders and an easy boxy fit allow you to wear it unbuttoned as a beach layer or tucked in for a more polished look. Naturally moisture-wicking and gets better with every wash.',
    image_url: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.2,
    review_count: 567,
    is_featured: false,
    is_new: true,
    tags: ['linen', 'oversized', 'summer', 'casual'],
    attributes: { material: 'Linen Blend', fit: 'Oversized', collar: 'Camp', sleeve: 'Short', available_sizes: ['XS', 'S', 'M', 'L', 'XL'] },
    meta_title: 'H&M Oversized Linen Shirt — Breathable Summer Style',
    meta_description: 'Shop H&M Oversized Linen Shirt. Breathable linen blend, drop shoulders, relaxed summer fit.',
  },
  {
    name: 'Under Armour Tech 2.0 T-Shirt',
    slug: 'under-armour-tech-20-tshirt',
    category: 'shirts',
    brand: 'Under Armour',
    sku: 'UA-TECH2-BLK-M',
    price: 25.00,
    compare_at_price: 35.00,
    short_description: 'Ultra-soft performance tee with anti-odor tech — for the gym or the street.',
    description: "Under Armour's Tech 2.0 T-Shirt is made with UA Tech fabric that feels incredibly soft and is fast-drying. Anti-odor technology prevents the growth of odor-causing microbes, and the lightweight knit provides a 4-way stretch for unrestricted movement during any workout.",
    image_url: 'https://images.unsplash.com/photo-1504198453319-5ce911bafcde?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.5,
    review_count: 3241,
    is_featured: false,
    is_new: false,
    tags: ['performance', 'athletic', 'anti-odor', 'gym'],
    attributes: { material: 'UA Tech Fabric', fit: 'Fitted', collar: 'Crew', sleeve: 'Short', stretch: '4-Way', available_sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'] },
    meta_title: 'Under Armour Tech 2.0 T-Shirt — Performance Athletic Tee',
    meta_description: 'Shop Under Armour Tech 2.0 T-Shirt. Anti-odor technology, 4-way stretch, ultra-soft UA Tech fabric.',
  },
  {
    name: 'Uniqlo AIRism Cotton Crew T-Shirt',
    slug: 'uniqlo-airism-cotton-crew-tshirt',
    category: 'shirts',
    brand: 'Uniqlo',
    sku: 'UQ-AIRISM-WHT-M',
    price: 19.90,
    compare_at_price: 29.90,
    short_description: 'The everyday essential — AIRism technology keeps you cool and fresh all day.',
    description: "Uniqlo's AIRism Cotton T-Shirt combines the natural softness of cotton with AIRism's moisture-wicking, quick-drying, and odor-fighting technology. A smooth, form-flattering fit makes it the perfect base layer or standalone tee for any occasion. The silicone print neck label eliminates irritation.",
    image_url: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.6,
    review_count: 8932,
    is_featured: true,
    is_new: false,
    tags: ['airism', 'cotton', 'everyday', 'essential'],
    attributes: { material: 'AIRism Cotton', fit: 'Regular', collar: 'Crew', sleeve: 'Short', available_sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'] },
    meta_title: 'Uniqlo AIRism Cotton Crew T-Shirt — Stay Cool All Day',
    meta_description: 'Shop Uniqlo AIRism Cotton T-Shirt. Moisture-wicking, quick-drying, all-day freshness.',
  },

  // ── PHONES (5) ────────────────────────────────────────────────────────────
  {
    name: 'Apple iPhone 15 Pro Max',
    slug: 'apple-iphone-15-pro-max',
    category: 'phones',
    brand: 'Apple',
    sku: 'APL-IP15PM-256',
    price: 1199.00,
    compare_at_price: null,
    short_description: 'Titanium design, A17 Pro chip, and a 48MP main camera system with 5× telephoto.',
    description: "The iPhone 15 Pro Max introduces a strong titanium design with the most powerful iPhone chip ever — the A17 Pro with a 6-core GPU. The 48MP main camera with second-generation sensor-shift OIS and a new 5× Telephoto camera let you capture every detail. USB 3 speeds via USB-C, and up to 29 hours video playback.",
    image_url: 'https://images.unsplash.com/photo-1695048133142-1a20484428d4?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.9,
    review_count: 4521,
    is_featured: true,
    is_new: false,
    tags: ['flagship', 'ios', 'titanium', '5g', 'camera'],
    attributes: { os: 'iOS 17', chip: 'A17 Pro', display: '6.7-inch Super Retina XDR', storage_options: ['256GB', '512GB', '1TB'], camera: '48MP Main + 12MP Ultra Wide + 12MP 5x Telephoto', battery: '4422 mAh', connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3' },
    meta_title: 'Apple iPhone 15 Pro Max — Titanium Flagship',
    meta_description: 'Shop Apple iPhone 15 Pro Max. A17 Pro chip, 48MP camera system, titanium design, USB-C.',
  },
  {
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    category: 'phones',
    brand: 'Samsung',
    sku: 'SAM-GS24U-256',
    price: 1299.99,
    compare_at_price: null,
    short_description: 'Built-in S Pen, 200MP camera, and Galaxy for next-level productivity.',
    description: 'The Samsung Galaxy S24 Ultra features a built-in S Pen for natural handwriting and sketching. The 200MP camera with 100× Space Zoom captures breathtaking detail. Galaxy transforms your productivity with Circle to Search, Live Translate, and AI-powered editing. The titanium frame is both premium and durable.',
    image_url: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.8,
    review_count: 3201,
    is_featured: true,
    is_new: false,
    tags: ['flagship', 'android', 's-pen', 'ai', '200mp'],
    attributes: { os: 'Android 14 / One UI 6.1', chip: 'Snapdragon 8 Gen 3', display: '6.8-inch Dynamic AMOLED 2X', storage_options: ['256GB', '512GB', '1TB'], camera: '200MP Main + 12MP Ultra Wide + 50MP 5x + 10MP 3x', battery: '5000 mAh', s_pen: true },
    meta_title: 'Samsung Galaxy S24 Ultra — 200MP Camera Phone',
    meta_description: 'Shop Samsung Galaxy S24 Ultra. Built-in S Pen, 200MP camera, Galaxy features.',
  },
  {
    name: 'Google Pixel 8 Pro',
    slug: 'google-pixel-8-pro',
    category: 'phones',
    brand: 'Google',
    sku: 'GOG-PX8P-128',
    price: 999.00,
    compare_at_price: 1099.00,
    short_description: 'Google Tensor G3 chip with AI-powered photography and 7 years of OS updates.',
    description: "The Google Pixel 8 Pro is Google's most intelligent phone. The custom Tensor G3 chip powers new features like Best Take, Magic Eraser, and Photo Unblur. The 50MP main camera with a larger sensor captures stunning images in any light, while Video Boost processes video frames independently for cinema-quality results. Guaranteed 7 years of OS and security updates.",
    image_url: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.7,
    review_count: 2134,
    is_featured: true,
    is_new: false,
    tags: ['flagship', 'android', 'ai', 'tensor', 'camera'],
    attributes: { os: 'Android 14', chip: 'Google Tensor G3', display: '6.7-inch LTPO OLED', storage_options: ['128GB', '256GB', '1TB'], camera: '50MP Main + 48MP Ultra Wide + 48MP 5x Telephoto', battery: '5050 mAh', updates: '7 years' },
    meta_title: 'Google Pixel 8 Pro — AI-Powered Photography',
    meta_description: 'Shop Google Pixel 8 Pro. Tensor G3 chip, 50MP camera, 7 years of OS updates, photo features.',
  },
  {
    name: 'OnePlus 12 5G',
    slug: 'oneplus-12-5g',
    category: 'phones',
    brand: 'OnePlus',
    sku: 'OP-OP12-256',
    price: 799.00,
    compare_at_price: 899.00,
    short_description: 'Snapdragon 8 Gen 3, Hasselblad camera tuning, and 100W SUPERVOOC charging.',
    description: 'The OnePlus 12 is a flagship killer with Snapdragon 8 Gen 3 performance and Hasselblad-tuned cameras. The 50MP main sensor with Sony LYT-808 captures rich, accurate colors, while 100W SUPERVOOC charging gets you from 0 to 100% in just 26 minutes. The 5400 mAh battery delivers a full day of heavy use.',
    image_url: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.6,
    review_count: 1876,
    is_featured: false,
    is_new: true,
    tags: ['flagship', 'android', 'fast-charge', 'hasselblad'],
    attributes: { os: 'OxygenOS 14 (Android 14)', chip: 'Snapdragon 8 Gen 3', display: '6.82-inch LTPO3 AMOLED', storage_options: ['256GB', '512GB'], camera: '50MP Sony LYT-808 + 48MP Ultra Wide + 64MP 3x Periscope', battery: '5400 mAh', charging: '100W Wired + 50W Wireless' },
    meta_title: 'OnePlus 12 5G — Flagship Performance at Value',
    meta_description: 'Shop OnePlus 12 5G. Snapdragon 8 Gen 3, Hasselblad cameras, 100W SUPERVOOC fast charging.',
  },
  {
    name: 'Nothing Phone (2a)',
    slug: 'nothing-phone-2a',
    category: 'phones',
    brand: 'Nothing',
    sku: 'NTH-PH2A-128',
    price: 349.00,
    compare_at_price: 399.00,
    short_description: 'Iconic Glyph Interface, clean Android, and a Dimensity 7200 Pro chip — style meets substance.',
    description: "The Nothing Phone (2a) brings the iconic Glyph Interface to a wider audience. The 50MP Sony IMX882 main camera with OIS captures crisp images day and night. Nothing OS delivers a clean, customizable Android experience with no bloatware. The unique see-through design and programmable Glyph lights make it the most distinctive mid-range phone.",
    image_url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.5,
    review_count: 987,
    is_featured: false,
    is_new: true,
    tags: ['android', 'glyph', 'mid-range', 'unique-design'],
    attributes: { os: 'Nothing OS 2.5 (Android 14)', chip: 'MediaTek Dimensity 7200 Pro', display: '6.7-inch AMOLED', storage_options: ['128GB', '256GB'], camera: '50MP Sony OIS Main + 50MP Ultra Wide', battery: '5000 mAh', glyph: true },
    meta_title: 'Nothing Phone (2a) — Iconic Glyph Interface',
    meta_description: 'Shop Nothing Phone (2a). Glyph Interface, clean Android, 50MP camera, transparent design.',
  },

  // ── ACCESSORIES (8) ──────────────────────────────────────────────────────
  {
    name: 'Apple AirPods Pro (2nd Gen)',
    slug: 'apple-airpods-pro-2nd-gen',
    category: 'accessories',
    brand: 'Apple',
    sku: 'APL-APP2-WHT',
    price: 249.00,
    compare_at_price: 279.00,
    short_description: 'Up to 2× more Active Noise Cancellation with Adaptive Audio and Personalised Spatial Audio.',
    description: "The Apple AirPods Pro (2nd generation) feature Apple's H2 chip for up to 2× more Active Noise Cancellation. Adaptive Audio dynamically blends ANC and Transparency mode based on your environment. Personalised Spatial Audio with dynamic head tracking places sound all around you. Up to 30 hours total listening time with the MagSafe Charging Case.",
    image_url: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.8,
    review_count: 6721,
    is_featured: true,
    is_new: false,
    tags: ['earbuds', 'anc', 'apple', 'spatial-audio', 'wireless'],
    attributes: { chip: 'Apple H2', anc: true, transparency_mode: true, battery_buds: '6 hours (ANC on)', battery_total: '30 hours', charging: 'MagSafe / Lightning / USB-C', water_resistant: 'IPX4', connectivity: 'Bluetooth 5.3' },
    meta_title: 'Apple AirPods Pro 2nd Gen — Best-in-Class ANC',
    meta_description: 'Shop Apple AirPods Pro 2nd Gen. 2× better ANC, Adaptive Audio, Personalised Spatial Audio, 30h total battery.',
  },
  {
    name: 'Samsung Galaxy Watch 6 Classic',
    slug: 'samsung-galaxy-watch-6-classic',
    category: 'accessories',
    brand: 'Samsung',
    sku: 'SAM-GW6C-47',
    price: 329.99,
    compare_at_price: 399.99,
    short_description: 'Iconic rotating bezel with advanced health tracking and Wear OS 4.',
    description: "The Samsung Galaxy Watch 6 Classic brings back the iconic rotating bezel for intuitive navigation, paired with the most advanced health sensors Samsung has ever built into a watch. Track sleep, measure body composition, get real-time ECG readings, and monitor blood oxygen all from your wrist. Wear OS 4 with One UI Watch 5 delivers a seamless Galaxy ecosystem experience.",
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.6,
    review_count: 2134,
    is_featured: true,
    is_new: false,
    tags: ['smartwatch', 'health', 'ecg', 'rotating-bezel', 'wear-os'],
    attributes: { os: 'Wear OS 4', display: '1.5-inch Super AMOLED', battery: '47mm: 425 mAh', health: ['ECG', 'Blood Oxygen', 'Sleep Coaching', 'Body Composition'], water_resistant: '5ATM + IP68', connectivity: 'Bluetooth 5.3, Wi-Fi 2.4/5GHz' },
    meta_title: 'Samsung Galaxy Watch 6 Classic — Advanced Health Smartwatch',
    meta_description: 'Shop Samsung Galaxy Watch 6 Classic. Rotating bezel, ECG, body composition, Wear OS 4.',
  },
  {
    name: 'Anker 737 PowerBank 24000mAh',
    slug: 'anker-737-powerbank-24000mah',
    category: 'accessories',
    brand: 'Anker',
    sku: 'ANK-737-BLK',
    price: 79.99,
    compare_at_price: 99.99,
    short_description: '140W total output portable charger — charge a MacBook Pro from 0–50% in 49 min.',
    description: 'The Anker 737 PowerBank delivers a massive 24000mAh capacity with 140W total output across three ports (USB-C × 2, USB-A × 1). The built-in smart display shows remaining charge percentage and power input/output wattage in real-time. Perfect for keeping laptops, phones, and tablets powered during long travel days.',
    image_url: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.7,
    review_count: 3412,
    is_featured: false,
    is_new: false,
    tags: ['powerbank', 'charging', 'usb-c', 'travel', 'laptop'],
    attributes: { capacity: '24000 mAh', total_output: '140W', ports: ['USB-C 140W', 'USB-C 18W', 'USB-A 18W'], smart_display: true, recharge_time: '~2 hours via 65W+' },
    meta_title: 'Anker 737 PowerBank 24000mAh — 140W Fast Charging',
    meta_description: 'Shop Anker 737 PowerBank. 24000mAh, 140W output, charges MacBook Pro. Smart display shows power stats.',
  },
  {
    name: 'Apple MagSafe Wallet',
    slug: 'apple-magsafe-wallet',
    category: 'accessories',
    brand: 'Apple',
    sku: 'APL-MSWL-TAN',
    price: 59.00,
    compare_at_price: null,
    short_description: 'Premium leather wallet that snaps magnetically to your iPhone — holds up to 3 cards.',
    description: 'The Apple MagSafe Wallet is crafted from European leather and attaches magnetically to iPhone 12 and later with a satisfying snap. Holds up to three cards or a small amount of cash. Find My integration lets you locate your wallet if it gets separated from your iPhone.',
    image_url: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.2,
    review_count: 876,
    is_featured: false,
    is_new: false,
    tags: ['magsafe', 'wallet', 'leather', 'iphone', 'find-my'],
    attributes: { material: 'European Leather', capacity: 'Up to 3 cards', compatible: 'iPhone 12 and later', find_my: true, attachment: 'MagSafe' },
    meta_title: 'Apple MagSafe Wallet — European Leather Card Holder',
    meta_description: 'Shop Apple MagSafe Wallet. Premium European leather, holds 3 cards, Find My integration.',
  },
  {
    name: 'Ray-Ban Aviator Classic',
    slug: 'ray-ban-aviator-classic',
    category: 'accessories',
    brand: 'Ray-Ban',
    sku: 'RB-AVI-GLD-G15',
    price: 154.00,
    compare_at_price: 195.00,
    short_description: 'The original gold frame Aviator with classic G-15 green lenses — iconic since 1937.',
    description: "Ray-Ban's Aviator Classic is the original and most recognized sunglass silhouette in the world. The gold metal double bridge frame and green G-15 lenses protect against UV rays while delivering natural color perception. Lightweight construction and spring hinges ensure all-day wearability.",
    image_url: 'https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.7,
    review_count: 4231,
    is_featured: false,
    is_new: false,
    tags: ['sunglasses', 'aviator', 'uv-protection', 'classic', 'iconic'],
    attributes: { frame: 'Gold Metal', lens: 'G-15 Green', uv_protection: 'UV400', lens_width: '58mm', bridge: '14mm', temple: '135mm' },
    meta_title: 'Ray-Ban Aviator Classic — Gold Frame G-15 Lens',
    meta_description: 'Shop Ray-Ban Aviator Classic. Original gold frame, G-15 green lenses, UV400 protection.',
  },
  {
    name: 'Sony WH-1000XM5 Headphones',
    slug: 'sony-wh-1000xm5-headphones',
    category: 'accessories',
    brand: 'Sony',
    sku: 'SNY-XM5-BLK',
    price: 349.99,
    compare_at_price: 399.99,
    short_description: "Industry-leading ANC with 8 microphones, 30-hour battery, and auto-pause.",
    description: "The Sony WH-1000XM5 redefines noise cancellation with 8 microphones and 2 processors working together to eliminate noise at all frequencies. Speak-to-Chat automatically pauses music when you start talking. 30-hour battery with quick charge (3 min charge = 3 hours of use). Ultra-lightweight folding design at just 250g.",
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.8,
    review_count: 5123,
    is_featured: true,
    is_new: false,
    tags: ['headphones', 'anc', 'sony', 'wireless', 'over-ear'],
    attributes: { driver: '30mm', frequency: '4Hz – 40,000Hz', battery: '30 hours (ANC on)', charging: 'USB-C, Quick Charge', anc: true, speak_to_chat: true, weight: '250g', connectivity: 'Bluetooth 5.2, Multipoint' },
    meta_title: 'Sony WH-1000XM5 Headphones — Industry-Leading ANC',
    meta_description: 'Shop Sony WH-1000XM5. Industry-leading ANC, 30h battery, 8 microphones, Speak-to-Chat.',
  },
  {
    name: 'JBL Charge 5 Portable Speaker',
    slug: 'jbl-charge-5-portable-speaker',
    category: 'accessories',
    brand: 'JBL',
    sku: 'JBL-CH5-BLK',
    price: 179.95,
    compare_at_price: 199.95,
    short_description: 'IP67 waterproof Bluetooth speaker with 20 hours battery and powerbank functionality.',
    description: "The JBL Charge 5 delivers JBL Pro Sound with a separate tweeter for high-frequency clarity and a bigger woofer for deep bass. IP67 waterproof and dustproof means it handles pool parties, beach days, and rainy adventures. PartyBoost connects multiple JBL speakers together for louder parties, and the built-in powerbank can charge your devices.",
    image_url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.7,
    review_count: 3241,
    is_featured: false,
    is_new: false,
    tags: ['speaker', 'bluetooth', 'waterproof', 'portable', 'party'],
    attributes: { battery: '20 hours', waterproof: 'IP67', charging: 'USB-C', powerbank: true, party_boost: true, connectivity: 'Bluetooth 5.1' },
    meta_title: 'JBL Charge 5 — IP67 Waterproof Portable Speaker',
    meta_description: 'Shop JBL Charge 5. IP67 waterproof, 20h battery, PartyBoost, powerbank. JBL Pro Sound.',
  },
  {
    name: 'Logitech MX Master 3S Mouse',
    slug: 'logitech-mx-master-3s-mouse',
    category: 'accessories',
    brand: 'Logitech',
    sku: 'LOG-MXM3S-GRA',
    price: 99.99,
    compare_at_price: 119.99,
    short_description: '8K DPI precision sensor, MagSpeed scroll wheel, and near-silent clicks.',
    description: "The Logitech MX Master 3S is the pinnacle of productivity mice. An 8000 DPI optical sensor tracks on any surface — including glass. MagSpeed Electromagnetic scroll wheel adjusts automatically between precise ratchet clicks and hyper-fast free-spinning mode. Near-silent clicks are 90% quieter while remaining crisp. Connect up to three devices via Bluetooth or Logi Bolt USB receiver.",
    image_url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&h=600&q=80',
    rating: 4.9,
    review_count: 4521,
    is_featured: true,
    is_new: false,
    tags: ['mouse', 'wireless', 'productivity', 'ergonomic', 'magspeed'],
    attributes: { sensor: '8000 DPI Optical', scroll: 'MagSpeed Electromagnetic', battery: '70 days', charging: 'USB-C', connections: 3, silent_clicks: true, compatibility: 'Windows, Mac, Linux, ChromeOS' },
    meta_title: 'Logitech MX Master 3S — 8K DPI Silent Wireless Mouse',
    meta_description: 'Shop Logitech MX Master 3S. 8000 DPI, MagSpeed scroll, near-silent clicks, 70-day battery.',
  },
];

async function seed() {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    await client.query(
      'TRUNCATE shop_product_images, shop_products, shop_categories RESTART IDENTITY CASCADE'
    );

    const categoryIds = {};
    for (const cat of categories) {
      const result = await client.query(
        `INSERT INTO shop_categories (name, slug, description, icon, image_url, sort_order)
         VALUES ($1, $2, $3, $4, $5, $6) RETURNING id`,
        [cat.name, cat.slug, cat.description, cat.icon, cat.image_url, cat.sort_order]
      );
      categoryIds[cat.slug] = result.rows[0].id;
    }
    console.log(`✅  Inserted ${categories.length} categories`);

    let productCount = 0;
    for (const p of products) {
      await client.query(
        `INSERT INTO shop_products
          (name, slug, short_description, description, price, compare_at_price, sku,
           category_id, category_slug, brand, in_stock, stock_quantity, image_url,
           rating, review_count, meta_title, meta_description, attributes,
           is_featured, is_new, tags)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21)`,
        [
          p.name, p.slug, p.short_description, p.description,
          p.price, p.compare_at_price || null, p.sku,
          categoryIds[p.category], p.category, p.brand,
          true, 100, p.image_url,
          p.rating, p.review_count,
          p.meta_title, p.meta_description,
          JSON.stringify(p.attributes),
          p.is_featured || false, p.is_new || false,
          p.tags,
        ]
      );
      productCount++;
    }
    console.log(`✅  Inserted ${productCount} products`);

    await client.query(`
      UPDATE shop_categories c
      SET product_count = (SELECT COUNT(*) FROM shop_products p WHERE p.category_id = c.id)
    `);

    await client.query('COMMIT');
    console.log('\n🎉  Database seeded successfully!\n');
    console.log('Categories:');
    categories.forEach(c => {
      const count = products.filter(p => p.category === c.slug).length;
      console.log(`  ${c.icon} ${c.name}: ${count} products`);
    });
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('❌  Seed failed:', err.message);
    throw err;
  } finally {
    client.release();
    await pool.end();
  }
}

seed().catch(err => {
  console.error(err);
  process.exit(1);
});
